# Generated by Django 6.0.3 on 2026-03-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('register_number', 'course')},
        ),
    ]
