# Generated by Django 6.0.3 on 2026-03-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_alter_student_register_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='register_number',
            new_name='roll_id',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_id', 'course')},
        ),
    ]
