# Generated by Django 6.0.3 on 2026-03-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_rename_register_number_student_roll_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_id',
            new_name='register_number',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('register_number', 'course')},
        ),
    ]
